//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int EmpID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int DeptID { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
        public string AddressLine { get; set; }
        public string City { get; set; }
        public System.DateTime DOJ { get; set; }
        public System.DateTime DOB { get; set; }
        public string Gender { get; set; }
        public decimal Salary { get; set; }
        public Nullable<decimal> Bonus { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
